-- sqlite
-- UP
CREATE TABLE BLOG_TAGS (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    blogId INTEGER NOT NULL,
    tag text NOT NULL,
    createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME NULL DEFAULT NULL,
    deletedAt DATETIME NULL DEFAULT NULL,
    isDeleted TINYINT(1) NOT NULL DEFAULT 0
);

CREATE TRIGGER blog_tags_updated_at
AFTER UPDATE ON BLOG_TAGS
FOR EACH ROW
BEGIN
    UPDATE BLOG_TAGS SET updatedAt = CURRENT_TIMESTAMP WHERE id = old.id;
END;

-- Down
DROP TABLE BLOG_TAGS;