-- sqlite
-- UP
CREATE TABLE USER (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    role INTEGER NOT NULL DEFAULT 0,
    name VARCHAR(255) NOT NULL,
    customId VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME NULL DEFAULT NULL,
    deletedAt DATETIME NULL DEFAULT NULL,
    isDeleted TINYINT(1) NOT NULL DEFAULT 0,

    UNIQUE (customId),
    UNIQUE (email)
);

CREATE TRIGGER user_updated_at
AFTER UPDATE ON USER
FOR EACH ROW
BEGIN
    UPDATE USER SET updatedAt = CURRENT_TIMESTAMP WHERE id = old.id;
END;

-- Down
DROP TABLE Pokemon;