-- sqlite
-- UP
CREATE TABLE BLOG_GUESTBOOK_LOG (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    userId text NOT NULL,
    ip text,
    contents text NOT NULL,
    createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME NULL DEFAULT NULL,
    deletedAt DATETIME NULL DEFAULT NULL,
    isDeleted TINYINT(1) NOT NULL DEFAULT 0
);

CREATE TRIGGER blog_guestbook_log_updated_at
AFTER UPDATE ON BLOG_GUESTBOOK_LOG
FOR EACH ROW
BEGIN
    UPDATE BLOG_GUESTBOOK_LOG SET updatedAt = CURRENT_TIMESTAMP WHERE id = old.id;
END;

-- Down
DROP TABLE BLOG_GUESTBOOK_LOG;