-- sqlite
-- UP
CREATE TABLE COMMENT (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    blogId INTEGER NOT NULL,
    content text NOT NULL,
    isReply TINYINT(1) NOT NULL DEFAULT 0,
    parentId INTEGER,
    createdBy text NOT NULL,
    createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME NULL DEFAULT NULL,
    deletedAt DATETIME NULL DEFAULT NULL,
    isDeleted TINYINT(1) NOT NULL DEFAULT 0
);

CREATE TRIGGER comment_updated_at
AFTER UPDATE ON COMMENT
FOR EACH ROW
BEGIN
    UPDATE COMMENT SET updatedAt = CURRENT_TIMESTAMP WHERE id = old.id;
END;

-- Down
DROP TABLE COMMENT;